### ISSUE TITLE
webpack一直加载失败

### ISSUE THREAD

**Issue by LiuXiao617111** [cipchk/ngx-ueditor#10]
我使用了webpack来打包，所以看你源码好像动态添加的script是固定的path地址，而不是webpack编译后的JS，所以可能不能兼容webpack，或者只能让我在dist里面放入这个文件，就是：没法打包ueditor。
其实我想问下，为什么我使用
> var ue=require('uediotr的js地址')

这样不行呢,这样获取的ue一直是一个空对象。是不是ueditor不支持commonjs,amd,cmd规范导致的。。只能用你那种的动态插入script来注入呢？

**Comment by cipchk** [comment]
这算是其一；
其二：是 ueditor 本身并不小，一并打包实在太大了，然而实际对 ueditor 的需求也只是个别页面。

**Comment by LiuXiao617111** [comment]
问题一：那是不是只能用你的package，然后用webpack把ueditor用file loader打包进dist？
问题二：我看到网上很多可以使用require来引入ueditor，既然用了require，那么不就是说支持commonjs，或者其他规范了吗，但是我看代码好像没一个符合的，这是为什么

**Comment by cipchk** [comment]
1：不必要，你可以直接放 `ueditor` 相关文件放到 `assets` 文件夹，angular-cli 会原样复制从而保存路径；亦或指向某个CDN。
2：我想大部分都是用 `require.js` 吧。

**Comment by LiuXiao617111** [comment]
我使用file-loader将ueditor全部打包进入了dist，然后在ts里面使用require（“ueditor”），这样的话访问全局ue就是未定义，没有在index里面添加script。
但是如果不用file-loader那么就可以访问全局的ue了。
我看了编译后的app.js,如果用file-loader那么就一句话，require（ueditor的地址），如果不用就是把ueditor源码引入的。不知道如果用了file-loader，应该这么引入，除了script

**Comment by cipchk** [comment]
抱歉，我提供不了你任何帮助，当初我对 `ueditor` 的 angular 版本封装，本身是出于市面并没有很友好的免费 angular 编辑器（虽然目前也没有）。

因此我并没有很深入的去挖掘 `file-loader` 的可用性，不过我想应该很困难，若 `ueditor.js` 被打包后自然全局性也就失效了，但无法保证 `ueditor.js` 内部是否需要对 `UE` 进行访问之类的，这可能还包括第三方插件。

**Comment by LiuXiao617111** [comment]
好的，还是谢谢你了。
