### ISSUE TITLE
linux系统，ng4下是不是不能使用，会报错

### ISSUE THREAD

**Issue by TerryDcl** [cipchk/ngx-ueditor#11]
![image](https://user-images.githubusercontent.com/32663110/31370050-2f98d9d4-adbb-11e7-8769-d5808d02f307.png)

**Comment by cipchk** [comment]
上传需要自行[配置](https://github.com/cipchk/ngx-ueditor#2使用)后端路径，有关更多细节请自行百度：ueditor 上传配置，若涉及跨域问题也请自行百度。
