### ISSUE TITLE
在同一个component中实例化使用三个ueditor时，初始化有的时候第三个ueditor没有初始化。

### ISSUE THREAD

**Issue by Crystal2Han** [cipchk/ngx-ueditor#12]
在同一个component中实例化使用三个ueditor时，刷新页面有的时候第三个ueditor没有初始化。找不到规律，有时候初始化2个，有时候3个都可以。

**Comment by Crystal2Han** [comment]
当第三个ueditor没有初始化成功是, onDestroy报错，parentNode is undefined

**Comment by Crystal2Han** [comment]
this.id在某些情况下getTime是一样的，ji建议通过其他方式创建唯一的id

![image](https://user-images.githubusercontent.com/31344426/32108934-ca3a9578-baf8-11e7-8836-0967778adc10.png)

**Comment by cipchk** [comment]
我想 **parentNode is undefined** 应该是 UEditor 产生的，能否帮忙定位在哪一行产生的错误呢？哪怕是 min 版本的 UEditor，这有助于我定位问题的根源。

`+new Date()` 绝大多数场景下是没有什么问题的。第三个无法实例，难道是由于 `id` 重复了？？

**Comment by Crystal2Han** [comment]
是的呀，打出来看log里ueditor实例的uid是重复的，new Date()是在大多数场景没有问题，但是在同一页面，异步加载的时候重复几率很高，几乎10有5-6次，我尝试在new Date().getTime()*Math.floor(Math.random()*100).  乘以一个随机数就不在出现重复。希望对你有帮助

**Comment by Crystal2Han** [comment]
parentNode undefined就是因为有一个ueditor的uid重复未加载，当偶然的机会全部加载成功则不报错。
