### ISSUE TITLE
使用1.0.7，升级依赖后，抛异常：Metadata version mismatch for module

### ISSUE THREAD

**Issue by BigBaBei** [cipchk/ngx-ueditor#14]
开发环境：
windows 10
angular 4，工程采用angular-cli  构建
webstorm.
初始版本：1.0.7
更新版本： 1.0.9

npm start 异常信息：
ERROR in Error: Metadata version mismatch for module  ===>/node_modules/ngx-ueditor/index.d.ts
found  version 4, expected 3, resolving symbol AppModule ===>/src/app/app.module.ts,

**Comment by cipchk** [comment]
若是 angular4 项目请使用 `1.0.8` 以下的版本，例如：

package.json:

```
"ngx-ueditor": "1.0.8"
```
