### ISSUE TITLE
部署路径问题

### ISSUE THREAD

**Issue by yudream** [cipchk/ngx-ueditor#15]
你好，因为这边项目部署时需要用到nginx服务器，然后会指定目录，比如test。
因此项目编译时我用了deploy-url=test这个参数，但是ngx-ueditor forRoot时传入的参数没法一起改掉，导致部署后无法加载ueditor。
请问是否有好的解决方案？万分感谢。

**Comment by cipchk** [comment]
Angular 允许在 `environment.ts` 中根据不同场景定制一些参数，有关更多细节见：[environment.ts](https://github.com/cipchk/ng-alain/blob/master/src/environments/environment.ts) & [environment.prod.ts](https://github.com/cipchk/ng-alain/blob/master/src/environments/environment.prod.ts) 之间的差异。

**Comment by yudream** [comment]
好主意，多谢。
