### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module 

### ISSUE THREAD

**Issue by SmallShrimp** [cipchk/ngx-ueditor#16]
ERROR in Error: Metadata version mismatch for module /node_modules/ngx-ueditor/index.d.ts, found version 4, expected 3

**Comment by SmallShrimp** [comment]
是不是依赖的angular版本不对应
我用的是 ^4.4.2

**Comment by cipchk** [comment]
please provider your `package.json`.

or, trying use:

```json
"ngx-ueditor": "1.0.8"
```

**Comment by wuhemei** [comment]
i have same problem``
"@angular/animations": "4.4.3",
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@angular/router": "4.4.3",
    "angular-baidu-maps": "^1.0.0",
    "angular-froala-wysiwyg": "^2.7.1",
    "angular-qq-maps": "^1.0.0",
    "angular-tree-component": "^5.0.0",
    "angular-web-storage": "^1.0.0",
    "chart.js": "^2.7.0",
    "core-js": "^2.5.1",
    "d3": "^4.10.0",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "g2": "^2.3.12",
    "g2-angular": "^1.0.0",
    "moment": "^2.18.1",
    "ng-tree-antd": "^1.0.0-bate",
    "ng-zorro-antd": "^0.5.3",
    "ng2-charts": "^1.6.0",
    "ng2-dnd": "^4.2.0",
    "ng2-file-upload": "^1.2.1",
    "ng2-img-cropper": "^0.9.0",
    "ngx-color-picker": "^4.3.1",
    "ngx-perfect-scrollbar": "^4.5.3",
    "ngx-ueditor": "^1.0.8",
    "rxjs": "^5.4.3",

**Comment by cipchk** [comment]
duplcated #14
