### ISSUE TITLE
ng4 使用报错Uncaught Error: not import language file，不是每次都报错，比如一开始正常，刷新几次页面就报异常

### ISSUE THREAD

**Issue by TerryDcl** [cipchk/ngx-ueditor#18]
![image](https://user-images.githubusercontent.com/32663110/33471434-5fc6fcec-d6a8-11e7-9c39-938482f1c0fb.png)

**Comment by cipchk** [comment]
能否提供你的所有代码明细吗？或者在 plunk 当中能重现问题步骤的 DEMO 呢？

**Comment by TerryDcl** [comment]
install的1.0.8版本的
<ueditor #u_answer [(ngModel)]="answerContent" id='u_answer' name='u_answer' [config]="config" (onReady)="answerAt()" required ></ueditor>

**Comment by TerryDcl** [comment]
现在又测出了新的问题，只要用鼠标滑轮滚动滚动条就会报下面的错误

![image](https://user-images.githubusercontent.com/32663110/33476663-b368c834-d6bd-11e7-984b-a22acf4b249d.png)

**Comment by cipchk** [comment]
能否提供一个 plnkr 的在线可重现的DEMO呢？谢谢

**Comment by sptrs** [comment]
这个问题我也出现了，不是每次都会出现
![image](https://user-images.githubusercontent.com/5369416/35085519-f62b2b28-fc63-11e7-9ca0-d9739140d226.png)

**Comment by cipchk** [comment]
语言文件的导入机制是 ueditor 内部自实现， ngx-ueditor 并未任何干预。

**Comment by cipchk** [comment]
长时间未提供更多信息，暂时关闭，若有问题，请重新提交 Issues。
