### ISSUE TITLE
用angular-starter怎样配置

### ISSUE THREAD

**Issue by leif2017** [cipchk/ngx-ueditor#19]
用angular-starter怎样配置,基本不能用

**Comment by cipchk** [comment]
在 `app.module` 文件里导入 `UEditorModule` 即可。倘若有具体的错误消息，麻烦提供一下。

**Comment by leif2017** [comment]
加你qq吧,我的qq2556772015

**Comment by leif2017** [comment]
我不是用的angular-cli构建的,是用angular-stater启动项的

**Comment by leif2017** [comment]
用的是webpack 3构建工具

**Comment by cipchk** [comment]
麻烦你提供更有效的信息给我，比如是不是存在 AOT 方面的问题？

**Comment by leif2017** [comment]
是的,存在这种问题,getEditor( ) not a function

**Comment by cipchk** [comment]
AOT的话的确会有问题，晚上我会发布一个支持AOT的版本。

**Comment by leif2017** [comment]
其实dev也存在问题,还有你的ueditor引入进去的文件没有打包压缩

**Comment by leif2017** [comment]
非常感谢,还有对angular4+版本的目前支持不是特别友好

**Comment by cipchk** [comment]
`min` 脚本这本身应该是 webpack 在做的事。angular4 的话可能要降低版本，不过今晚一并处理 v4 & v5 的兼容问题

**Comment by leif2017** [comment]
ok,thx

**Comment by leif2017** [comment]
其实用angular-starter项目启动,无论是dev还是aot好像都会出现各种的错误

**Comment by cipchk** [comment]
dev 模式应该不会有问题，而aot可能会有问题

**Comment by cipchk** [comment]
@leif2017 我刚利用 angular-starter 引用  `ngx-ueditor` 包括 aot 都是没有问题

jpg:
![aot](https://user-images.githubusercontent.com/2987467/33601294-beb3f44e-d9e6-11e7-9c0d-61b4260102bc.png)

**Comment by leif2017** [comment]
没有任何改动?

**Comment by cipchk** [comment]
是，只有两处修改：

**app.module.ts**

```ts
import { UEditorModule } from 'ngx-ueditor';

    UEditorModule.forRoot({
        // 指定ueditor.js路径目录
        path: 'assets/ueditor/',
        // 默认全局配置项
        options: {
            themePath: '/assets/ueditor/themes/'
        }
    }),
```

**home.component.ts**

```html
<ueditor [(ngModel)]="full_source"></ueditor>
```

```ts
full_source: '';
```

jpg:
![tim 20171205182246](https://user-images.githubusercontent.com/2987467/33602117-4ee37a88-d9e9-11e7-9cd4-b6015705231e.png)

**Comment by leif2017** [comment]
aot 之后

**Comment by leif2017** [comment]
aot之后报以下错误
![1512531529 1](https://user-images.githubusercontent.com/29476463/33643525-9e6c2a00-da7a-11e7-8a74-ce518e98c154.png)

**Comment by leif2017** [comment]
angular4+我需要哪个版本的?

**Comment by leif2017** [comment]
我现在用的是angular4.3.1版本,目前用的ngx-ueditor是1.0.8版本,aot之后是版本不匹配这个错误

**Comment by leif2017** [comment]
![Uploading 1512532127(1).png…]()
![Uploading 1512532170(1).png…]()

**Comment by leif2017** [comment]
![1512532089 1](https://user-images.githubusercontent.com/29476463/33643760-195b9d30-da7c-11e7-8252-cda3b05dae4f.png)
![1512532127 1](https://user-images.githubusercontent.com/29476463/33643761-1996e282-da7c-11e7-8285-97a07770f356.png)
![1512532170 1](https://user-images.githubusercontent.com/29476463/33643763-1a72a2ae-da7c-11e7-83d0-8e199361fcff.png)

**Comment by cipchk** [comment]
v4的话，指定一个固定版本号：

```
"ngx-ueditor": "1.0.8"
```

**Comment by cipchk** [comment]
长时间未提供更多信息，暂时关闭，若有问题，请重新提交 Issues。

**Comment by leif2017** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
好的,谢谢



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2018年02月27日 15:31，卡色<notifications@github.com> 写道： 


长时间未提供更多信息，暂时关闭，若有问题，请重新提交 Issues。
