### ISSUE TITLE
帮我看一下,angular4.1.3报错是怎么回事

### ISSUE THREAD

**Issue by dllcnx** [cipchk/ngx-ueditor#20]
![tim 20171208134925](https://user-images.githubusercontent.com/20491834/33752805-db025250-dc1e-11e7-89da-d8fd3b586db7.png)
![tim 20171208134942](https://user-images.githubusercontent.com/20491834/33752810-ddcd5e76-dc1e-11e7-95c7-4901ef8fbdfa.png)

**Comment by cipchk** [comment]
duplcated #14
