### ISSUE TITLE
无法获取ueditor.config.js和ueditor.all.js文件导致引入失败

### ISSUE THREAD

**Issue by wanxiye** [cipchk/ngx-ueditor#21]
npm install后在app.module.ts中import UEditorModule并指定ueditor.js路径目录: path: '/assets/ueditor/':
![1512718802 1](https://user-images.githubusercontent.com/34365588/33756299-c6f41f8a-dc2f-11e7-97de-bad6cc6a7a2f.png)
将相关文件放置在assets目录下：
![1512719013 1](https://user-images.githubusercontent.com/34365588/33756323-e7b98f16-dc2f-11e7-9f2d-c9ae8b5659ca.png)
项目运行后报错：
![1512718954 1](https://user-images.githubusercontent.com/34365588/33756332-f6a032fa-dc2f-11e7-9025-e72875d25caa.png)
ueditor.config.js和ueditor.all.js文件已经放置在assets目录下，但是项目运行时却报错无法访问到这两个文件导致加载失败，请问该如何处理？

**Comment by cipchk** [comment]
检查一下 base-href

**Comment by wanxiye** [comment]
index.html中配置的base href 为：
 ![1512720937 1](https://user-images.githubusercontent.com/34365588/33757114-af1a119a-dc33-11e7-9560-03df16f3e3ac.png)
app.module.ts中指定的ueditor.js路径目录为 '/assets/ueditor/'
![1512718802 1](https://user-images.githubusercontent.com/34365588/33757174-f7045826-dc33-11e7-8537-ed8676616bf1.png)

**Comment by cipchk** [comment]
我看请求 `ueditor.config.js` 返回的是 err_aborted；试着重启 `ng serve` 呢？

**Comment by hnxuruochen** [comment]
您好，关于这个问题是这样的，想请教一下。
首先，我们不是用angular-cli生成的项目，而是用官网教程的webpack包，地址在这里：https://angular.io/guide/webpack
就目前的研究，有一些差异，首先我们使用的是webpack dev server启动，而不是ng serve。虽然据了解ng serve本身也是包装了webpack，但是不清楚配置文件在哪。而webpack启动包里面对webapck进行了配置，对不同的文件都使用了loader进行加载，然后哈希了名字，使得代码里面直接使用路径（比如/assets/a.jpg）是无法访问到的（但在html里面可以这么使用，因为编译时会被替换）。
这样就导致了没法直接使用路径配置Editor这个模块，不知道对此您有何办法？

**Comment by cipchk** [comment]
对于 cli 而言 `assets` 会被当成一个普通目录，好像是使用 `copy-webpack-plugin` 插件吧，细节我没深究。有关 angular cli 转换成 webpack 打包的方式，可以利用 angular cli 创建一个空项目，然后运行 `ng eject` 将 angular cli 项目转换成 webpack 项目；或许你可以根据这种形式了解一些细节。

当然 UEditor 所需要的资源也可以采用远程 cdn 链接，亦或在 `<head>` 加入相应的链接，虽然并不是很好。

**Comment by cipchk** [comment]
长时间未提供更多信息，暂时关闭，若有问题，请重新提交 Issues。
