### ISSUE TITLE
Ueditor 页面可以显示，但是会报错 If ngModel is used within a form tag

### ISSUE THREAD

**Issue by zjinger** [cipchk/ngx-ueditor#22]
加上 [(ngModel)]会报错
<ueditor [(ngModel)]="full_source" [config]="config"></ueditor>

If ngModel is used within a form tag, either the name attribute must be set or the form   control must be defined as 'standalone' in ngModelOptions.

去掉 ngModel 就不会报错
<ueditor  [config]="config"></ueditor>

环境：
Angular 5.0.0
ueditor 1.4.3.3
ngx-ueditor1.1.0

**Comment by cipchk** [comment]
若是在一个 `<form>` 内使用 `ngModel` 必须指定 `name` 属性，这是 Angular 的要求。
