### ISSUE TITLE
Error: StaticInjectorError[ElementRef]: 在angularjs5里报这种错误

### ISSUE THREAD

**Issue by gaona233** [cipchk/ngx-ueditor#23]
![mfak 1__admwr hs27gnozt](https://user-images.githubusercontent.com/22739329/34476359-0b2b85fe-efcb-11e7-8da3-07d868dc4202.png)

![ugot3 dqe n crisd vv](https://user-images.githubusercontent.com/22739329/34476369-28bd7730-efcb-11e7-876a-ec891a617169.png)

![s z pd mlxz 9n494wxg 8](https://user-images.githubusercontent.com/22739329/34476375-330a537a-efcb-11e7-8044-569dcba1bc8b.png)

![pfw 2 ow0 c r6lcqvyoe5](https://user-images.githubusercontent.com/22739329/34476380-3a018a04-efcb-11e7-8196-c8d278ccde89.png)

**Comment by cipchk** [comment]
![tim 20180102151447](https://user-images.githubusercontent.com/2987467/34476877-aee9b8f6-efcf-11e7-9b85-dc76cbfd2b85.png)

**Comment by gaona233** [comment]
我已经该成这样子了，但是还是这个报错
![snql p06ii cmkln245rnp](https://user-images.githubusercontent.com/22739329/34478696-54379f14-efdd-11e7-8adf-581641ba4854.png)
![vv3aq18_hh6 u s6g aw3t](https://user-images.githubusercontent.com/22739329/34478704-5bc084da-efdd-11e7-9570-6537dd16ee0d.png)
