### ISSUE TITLE
ng5中使用AOT编译时报错 Function expressions are not supported in decorators in 'NgModule'

### ISSUE THREAD

**Issue by aa754105233** [cipchk/ngx-ueditor#25]
![image](https://user-images.githubusercontent.com/32331668/34753954-e9fa98da-f5f5-11e7-8df6-7c419c505dfd.png) 如图所示 引入UeditorModule后进行AOT编译后就出现此错误

**Comment by aa754105233** [comment]
后来发现使用版本1.0.8则可以正常AOT编译，使用1.1.0会出现这个错误

**Comment by cipchk** [comment]
1.1.0 只支持 v5
