### ISSUE TITLE
ngx-ueditor与ng5冲突

### ISSUE THREAD

**Issue by gaona233** [cipchk/ngx-ueditor#26]
每次执行npm start 时会产生一下错误导致程序无法启动
/**
 *
ERROR in TypeError: staticSymbol.assertNoMembers is not a function
    at AotSummaryResolver.resolveSummary (F:\Workspace\WEB - Copy - Copy\src\sentations\web\node_modules\@angular\compiler\bundles\compiler.umd.js:31928:2
    at CompileMetadataResolver._loadSummary (F:\Workspace\WEB - Copy - Copy\spresentations\web\node_modules\@angular\compiler\bundles\compiler.umd.js:14706)
    at CompileMetadataResolver.isDirective (F:\Workspace\WEB - Copy - Copy\srresentations\web\node_modules\@angular\compiler\bundles\compiler.umd.js:15003)
    at CompileMetadataResolver._getTypeDescriptor (F:\Workspace\WEB - Copy - y\src\presentations\web\node_modules\@angular\compiler\bundles\compiler.umd.j5269:18)
    at F:\Workspace\WEB - Copy - Copy\src\presentations\web\node_modules\@angr\compiler\bundles\compiler.umd.js:15131:78
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (F:\Workspace\WEB - Copy -py\src\presentations\web\node_modules\@angular\compiler\bundles\compiler.umd.15114:49)
    at visitLazyRoute (F:\Workspace\WEB - Copy - Copy\src\presentations\web\n_modules\@angular\compiler\bundles\compiler.umd.js:29937:104)
    at visitLazyRoute (F:\Workspace\WEB - Copy - Copy\src\presentations\web\n_modules\@angular\compiler\bundles\compiler.umd.js:29941:17)
    at AotCompiler.listLazyRoutes (F:\Workspace\WEB - Copy - Copy\src\presentons\web\node_modules\@angular\compiler\bundles\compiler.umd.js:29905:20)
    at AngularCompilerProgram.listLazyRoutes (F:\Workspace\WEB - Copy - Copy\\presentations\web\node_modules\@angular\compiler-cli\src\transformers\progras:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (F:\Workspace\WEB - C - Copy\src\presentations\web\node_modules\@angular\compiler-cli\src\ngtools_.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (F:\Workspace\WEB - Co- Copy\src\presentations\web\node_modules\@ngtools\webpack\src\angular_compilplugin.js:248:66)
    at Promise.resolve.then.then (F:\Workspace\WEB - Copy - Copy\src\presentans\web\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:562:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)

 *
 */

感觉是和我这个框架的一些插件冲突了

**Comment by cipchk** [comment]
从错误上看没有迹象表明是 ngx-ueditor 引起的，建议看是不是你所使用的版本比较低？

**Comment by gaona233** [comment]
我用的就是1.1.0， 
我这边package.json

 "dependencies": {
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "5.0.0",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@angular/router": "5.0.0",
    "@ngx-translate/core": "8.0.0",
    "@ngx-translate/http-loader": "2.0.0",
    "@swimlane/ngx-datatable": "11.1.2",
    "ag-grid": "14.2.0",
    "ag-grid-angular": "14.2.0",
    "angular-tree-component": "6.0.0",
    "angular2-text-mask": "8.0.4",
    "angular2-toaster": "4.0.1",
    "bootstrap": "3.3.7",
    "chart.js": "2.7.1",
    "classlist.js": "1.1.20150312",
    "codemirror": "5.31.0",
    "core-js": "2.4.1",
    "easy-pie-chart": "2.1.7",
    "enhanced-resolve": "3.3.0",
    "font-awesome": "4.7.0",
    "fullcalendar": "3.6.2",
    "intl": "1.2.5",
    "jqcloud2": "2.0.3",
    "jquery": "3.2.1",
    "jquery-slimscroll": "1.3.8",
    "jquery-sparkline": "2.4.0",
    "jquery.browser": "0.1.0",
    "jquery.flot.tooltip": "github:krzysu/flot.tooltip",
    "lodash": "4.17.4",
    "modernizr": "3.5.0",
    "moment": "2.19.1",
    "ng2-charts": "1.6.0",
    "ng2-dnd": "4.2.0",
    "ng2-file-upload": "1.2.1",
    "ng2-img-cropper": "0.9.0",
    "ng2-select": "1.2.0",
    "ng2-table": "1.3.2",
    "ng2-validation": "4.2.0",
    "ngx-bootstrap": "2.0.0-beta.8",
    "ngx-chips": "1.5.9",
    "ngx-color-picker": "5.0.1",
    "ngx-infinite-scroll": "0.6.1",
    "node-sass": "4.5.3",
    "rxjs": "5.5.2",
    "screenfull": "3.3.2",
    "simple-line-icons": "2.4.1",
    "spinkit": "1.2.5",
    "summernote": "0.8.8",
    "sweetalert": "1.1.3",
    "ts-helpers": "1.1.1",
    "weather-icons": "github:erikflowers/weather-icons",
    "web-animations-js": "2.2.1",
    "zone.js": "0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.3",
    "@angular/compiler-cli": "5.0.0",
    "@angular/language-service": "5.0.0",
    "@types/codemirror": "0.0.50",
    "@types/jasmine": "2.5.53",
    "@types/jasminewd2": "2.0.2",
    "@types/lodash": "4.14.71",
    "@types/node": "6.0.60",
    "codelyzer": "4.0.1",
    "jasmine-core": "2.6.2",
    "jasmine-spec-reporter": "4.1.0",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.2.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-read-json": "1.1.0",
    "loaders.css": "0.1.2",
    "napa": "3.0.0",
    "protractor": "5.1.2",
    "ts-node": "3.2.0",
    "tslint": "5.7.0",
    "typescript": "2.4.2",
    "webdriver-manager": "10.2.5"
  }

**Comment by cipchk** [comment]
并没有看到 `package.json` 引用了 `ngx-ueditor`

**Comment by gaona233** [comment]
贴错了，是这个
 "dependencies": {
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "5.0.0",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@angular/router": "5.0.0",
    "@ngx-translate/core": "8.0.0",
    "@ngx-translate/http-loader": "2.0.0",
    "@swimlane/ngx-datatable": "11.1.2",
    "ag-grid": "14.2.0",
    "ag-grid-angular": "14.2.0",
    "angular-tree-component": "6.0.0",
    "angular2-text-mask": "8.0.4",
    "angular2-toaster": "4.0.1",
    "bootstrap": "3.3.7",
    "chart.js": "2.7.1",
    "classlist.js": "1.1.20150312",
    "codemirror": "5.31.0",
    "core-js": "2.4.1",
    "easy-pie-chart": "2.1.7",
    "enhanced-resolve": "3.3.0",
    "font-awesome": "4.7.0",
    "fullcalendar": "3.6.2",
    "intl": "1.2.5",
    "jqcloud2": "2.0.3",
    "jquery": "3.2.1",
    "jquery-slimscroll": "1.3.8",
    "jquery-sparkline": "2.4.0",
    "jquery.browser": "0.1.0",
    "jquery.flot.tooltip": "github:krzysu/flot.tooltip",
    "lodash": "4.17.4",
    "modernizr": "3.5.0",
    "moment": "2.19.1",
    "ng2-charts": "1.6.0",
    "ng2-dnd": "4.2.0",
    "ng2-file-upload": "1.2.1",
    "ng2-img-cropper": "0.9.0",
    "ng2-select": "1.2.0",
    "ng2-table": "1.3.2",
    "ng2-validation": "4.2.0",
    "ngx-bootstrap": "2.0.0-beta.8",
    "ngx-chips": "1.5.9",
    "ngx-color-picker": "5.0.1",
    "ngx-infinite-scroll": "0.6.1",
    "ngx-ueditor": "^1.1.0",
    "node-sass": "4.5.3",
    "rxjs": "5.5.2",
    "screenfull": "3.3.2",
    "simple-line-icons": "2.4.1",
    "spinkit": "1.2.5",
    "summernote": "0.8.8",
    "sweetalert": "1.1.3",
    "ts-helpers": "1.1.1",
    "weather-icons": "github:erikflowers/weather-icons",
    "web-animations-js": "2.2.1",
    "zone.js": "0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.3",
    "@angular/compiler-cli": "5.0.0",
    "@angular/language-service": "5.0.0",
    "@types/codemirror": "0.0.50",
    "@types/jasmine": "2.5.53",
    "@types/jasminewd2": "2.0.2",
    "@types/lodash": "4.14.71",
    "@types/node": "6.0.60",
    "codelyzer": "4.0.1",
    "jasmine-core": "2.6.2",
    "jasmine-spec-reporter": "4.1.0",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.2.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-read-json": "1.1.0",
    "loaders.css": "0.1.2",
    "napa": "3.0.0",
    "protractor": "5.1.2",
    "ts-node": "3.2.0",
    "tslint": "5.7.0",
    "typescript": "2.4.2",
    "webdriver-manager": "10.2.5"
  }

**Comment by cipchk** [comment]
这个我就不清楚了，你可以试着看能不能升级 angular & angular cli 至最新版本，能不能解决这一问题。

**Comment by gaona233** [comment]
可以了，谢谢，我把angular 版本变成了 ^5.0.0就可以了
