### ISSUE TITLE
运行项目的时候提示版本问题？请问一下我需要怎么才能解决这个问题？

### ISSUE THREAD

**Issue by yandel789** [cipchk/ngx-ueditor#30]
ERROR in Metadata version mismatch for module E:/weiaixingzou/admin/node_modules/ngx-ueditor/index.d.ts, found version 4, expected 3, resolving symbol

**Comment by cipchk** [comment]
v4的话，指定一个固定版本号：

```
"ngx-ueditor": "1.0.8"
```
