### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by Shakell** [cipchk/ngx-ueditor#32]
你好，我完成 UEditorModule 模块导入到项目后，在模版文件中加入
<ueditor [(ngModel)]="full_source" 
         [config]="{...}"
         [loadingTip]="'加载中……'"
         (onReady)=""
         (onDestroy)=""
         (onContentChange)=""></ueditor>

然后浏览器显示解析错误：
Parser Error: Unexpected token ., expected identifier, keyword, or string at column 2 in [{...}] in ng:///AppModule/AppComponent.html@1:9 ("<ueditor [(ngModel)]="full_source"
         [ERROR ->][config]="{...}"
         [loadingTip]="'加载中……'"
         (onReady)=""
"): ng:///AppModule/AppComponent.html@1:9

请问我是什么地方配置错了，感谢

**Comment by cipchk** [comment]
请给出完整的代码。

**Comment by Shakell** [comment]
**app.component.html**
`<ueditor [(ngModel)]="full_source"
         [config]="{...}"
         [loadingTip]="'加载中……'"
         (onReady)=""
         (onDestroy)=""
         (onContentChange)=""></ueditor>
`
**app.module.ts**
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';


import { AppComponent } from './app.component';

import { UEditorModule } from 'ngx-ueditor';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    UEditorModule.forRoot({
            // 指定ueditor.js路径目录
            path: 'assets/ueditor/',
            // 默认全局配置项
            options: {
                themePath: '/assets/ueditor/themes/'
            }
        })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`
**`assets 文件夹`**
<img width="258" alt="2018-04-22 19 28 16" src="https://user-images.githubusercontent.com/33541501/39097929-784cd18a-4663-11e8-9070-fc97e2313d4e.png">

**Comment by cipchk** [comment]
请给出完整错误行的代码，建议是完整的 `<ueditor></ueditor>` 部分。

**Comment by Shakell** [comment]
<ueditor [(ngModel)]="full_source" [config]="{...}" [loadingTip]="'加载中……'" (onReady)="" (onDestroy)="" (onContentChange)=""></ueditor>

这个就是<ueditor></ueditor>部分 是要在这里面添加什么东西吗

**Comment by cipchk** [comment]
请给出完整错误行的代码，建议是完整的 `<ueditor></ueditor>` 部分。
请给出完整错误行的代码，建议是完整的 `<ueditor></ueditor>` 部分。
请给出完整错误行的代码，建议是完整的 `<ueditor></ueditor>` 部分。

**Comment by Shakell** [comment]
<ueditor [(ngModel)]="full_source" [config]="{...}" [loadingTip]="'加载中……'" (onReady)="" (onDestroy)="" (onContentChange)=""></ueditor>

这个就是完整的错误行代码

**Comment by cipchk** [comment]
```
[config]="{...}"
```

你认这是合法的吗？
