### ISSUE TITLE
本地调试这个组件时，弹出对话框默认样式无效

### ISSUE THREAD

**Issue by SnekTech** [cipchk/ngx-ueditor#35]
![ueditor-bug-snapshort](https://user-images.githubusercontent.com/32608999/40300281-685cd81e-5d1b-11e8-8c56-26ea946a1fcf.png)
我首先在自己的项目中添加UEditorModule并在模板上应用，编辑器的功能是完好的，但是弹出对话框的样式都消失了，如标签页span元素的背景渐变和边框等等。
后来我克隆了完整的ngx-ueditor仓库，`npm i`后`ng serve`，demo组件在浏览器中的效果依然有bug。
然而在GitHub Pages上面的demo显然是完好的。
![ueditor-origin-snapshort](https://user-images.githubusercontent.com/32608999/40301093-99de7d32-5d1d-11e8-97a3-6bd4d43cc408.png)
我个人猜测这个问题在于路径，于是**显示地**配置了theme和themePath为默认配置（我没有写自己的css），但是这个bug依然存在。
目前我没有其他的思路来解决这个问题，也不太清楚这个bug的根本原因是在于我的使用方式还是module本身，希望作者（或者任何能帮助我的人）能给我一点提示（syf_ynu@foxmail.com， 或者直接回复issue）。

**Comment by cipchk** [comment]
建议始终配置 `UEditorModule.forRoot()` 的 `UEDITOR_HOME_URL` 值，因为它是对话框等的基础路径。

https://github.com/cipchk/ngx-ueditor/blob/master/src/app/app.module.ts#L28

**Comment by SnekTech** [comment]
感谢您的回复！@cipchk
这一步我是按照README.md来做的，在我自己的app.module.ts和完整clone的ngx-ueditor仓库的demo代码中，都使用了这个配置，然而我还是遇到了默认样式失效的问题，并且我并没有修改过clone下来的代码。使用开发者工具debug对话框，可以发现span等元素确实没有对应的css规则代码。
另外，在assets/ueditor/目录下面的index.html文件，如果我直接用浏览器打开，是没有问题的，所有的默认样式会正常显示，只是在angular中会出现问题，或许这与View Encapsulation有关？

**Comment by cipchk** [comment]
其实有一个简单又有效的办法，打开 chrome 的 network 面板，就知道对话框资源加载状态，就知道路径是否写对了。

**Comment by SnekTech** [comment]
新技能Get！
分析了一下请求后，发现问题所在了。请求dialogbase.css文件时，URL错误
浏览器请求（404）：
http://localhost:4200/assets/ueditor/dialogs/video/assets/ueditor/themes/default/dialogbase.css?cache=0.7331664243958836
浏览/assets/ueditor/dialogs/video文件夹发现确实没有对应的文件：
![default](https://user-images.githubusercontent.com/32608999/40310932-efdd6356-5d40-11e8-9bde-931bde6a8821.png)
分析弹出对话框的iframe，可以从head标签中看到引用了dialogbase.css和video.css：
![default](https://user-images.githubusercontent.com/32608999/40311957-082fdcba-5d44-11e8-853a-267eea4d6e08.png)
但是基础的dialogbase.css文件并没有通过正确的路径引用到。从`href='./assets/ueditor...'`可以看到这里使用的是相对路径，因此在请求的URL前面冗余了`/assets/ueditor/dialogs/video`；如果点击其他按钮，前面冗余的路径也不相同。

浏览video.html的源码，发现并没有引用dialogbase.css的`<link>`标签，可见这个标签是动态添加的。目前来看，如果把这个动态添加的`<link>`标签的href属性修改为绝对路径`href='/assets/ueditor...'`，就能正确得到默认样式了。
这个动态加载的过程应该如何控制呢？我本地的代码是直接clone的master分支，UEditorModule.forRoot()的配置应该没有问题。因此我去查看了ueditor/dialogs/internal.js的源码，发现了这么一行：
![default](https://user-images.githubusercontent.com/32608999/40313018-0703e540-5d47-11e8-85a2-746940d4b7a0.png)
然后我用浏览器打断点debug，分析变量值。

**首先是GitHub Pages上面的正确demo：**
![default](https://user-images.githubusercontent.com/32608999/40313164-80bd5628-5d47-11e8-8a85-2ce589cbeba7.png)

**然后是我clone的本地仓库上有bug的demo：**
![default](https://user-images.githubusercontent.com/32608999/40313246-d00a627a-5d47-11e8-928b-3152b63e349a.png)
可以看到，正确demo的href属性使用的是绝对路径而不是相对路径。正是这个相对路径导致了请求URL前面的冗余。
于是我尝试在UEditorModule.forRoot()中显示地配置themePath为绝对路径（`/assets/ueditor/themes/`），终于解决了这个问题，得到了具有默认样式的弹出框。
> 原来第一次想到的竟然是正确的解决方案，可能当时路径写错了，导致没有调试成功

最后，我再次看了作者配置UEDITOR_HOME_URL的代码，发现在在本地调试时使用`'.'`拼接字符串实现相对路径。我把它改为空字符串，并取消themePath的显示配置，同样得到了具有默认样式的弹出框。那么还是想请教您@cipchk，为什么这里要使用相对路径而不是绝对路径呢？

另外，如果ueditor.config.js的调用在ueditor.all.min.js之后，浏览器会报错（调换顺序后错误消失）；同时还会报错说没有引入语言文件，然而在显示地配置zh-cn.js之后，这个错误并不会消失。但是这些错误貌似并不影响编辑器的正常使用。（在官方demo的控制台中除了后端配置没有其他报错。）

如果您读到这里，真的很感谢您付出的时间，希望有一天我有足够的技术实力向您和您的组织提交代码！

**Comment by cipchk** [comment]
[themePath](http://fex.baidu.com/ueditor/#start-config) 其实所有 UEditor 跟路径相关都有相应的配置。

而跟 `UEditorModule.forRoot({ js: [] })` 相关的可能还包括 `<base>` 部分。
