### ISSUE TITLE
Angular 6 在reactiveForm 中使用是报错： a.replace is not a function

### ISSUE THREAD

**Issue by ESCxjl** [cipchk/ngx-ueditor#37]
hello， 你好： 
  我在我们的Angular项目中使用时，` <ueditor formControlName="content"></ueditor>`

报如下错： 

![2018-05-24 4 16 11](https://user-images.githubusercontent.com/21059943/40473377-916403ea-5f6e-11e8-8ba9-d35c2a98ae1d.png)

不知是什么原因，能否帮忙解答下？谢谢。

**Comment by Ricbet** [comment]
我也遇到这个问题，我把版本回退到2.1.0就好了

**Comment by cipchk** [comment]
duplcation of #43

**Comment by zhangjinsong** [comment]
那这个问题需要怎么解决

**Comment by cipchk** [comment]
升级至最新版本。

**Comment by zhangjinsong** [comment]
![image](https://user-images.githubusercontent.com/12949599/46722798-fc0bbd80-cca8-11e8-8e44-546888a05a2f.png)

升级后出现错误
