### ISSUE TITLE
UE.getEditor is not a function

### ISSUE THREAD

**Issue by AIxiuxiu** [cipchk/ngx-ueditor#38]
clone demo项目，刷新直接如下报错
_UE.getEditor is not a function. (In 'UE.getEditor(_this.id, opt)', 'UE.getEditor' is undefined)_
我自己的项目也一样，请问怎么解决呀！难道不能刷新吗

**Comment by billyshen26** [comment]
同样的问题，本地ng serve 没问题， 但到服务器 不管是ng build 还是ng build prod 都会报这个错，奇怪的是第一次是可以，刷新下就不行了

**Comment by billyshen26** [comment]
反复测试了下 ，感觉和浏览器缓存有关 ，清理缓存后已经正常了。等待进一步测试

**Comment by emondora** [comment]
同样的问题

**Comment by chendachao** [comment]
这个问题和配置文件的引入顺序有关，请参照这个[PR](https://github.com/cipchk/ngx-ueditor/pull/45)
