### ISSUE TITLE
angular5 报错ngDevMode

### ISSUE THREAD

**Issue by fujuhao** [cipchk/ngx-ueditor#39]
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-ueditor/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by cipchk** [comment]
duplcated of #36

**Comment by fujuhao** [comment]
core.js:1449 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[UEditorComponent -> ElementRef]: 
  StaticInjectorError(Platform: core)[UEditorComponent -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!

**Comment by fujuhao** [comment]
前面的问题
node_modules/ngx-ueditor/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.　　
这个我去掉了ngx-ueditor里的　不报错了，
第二个问题又出来了如下：

core.js:1449 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[UEditorComponent -> ElementRef]:
StaticInjectorError(Platform: core)[UEditorComponent -> ElementRef]:
NullInjectorError: No provider for ElementRef!

**Comment by cipchk** [comment]
1. 最新版本只支持 angular6
2. 移除 `node_modules` & `package-lock.json`
3. `npm i`

**Comment by fujuhao** [comment]
是移除　ngx-ueditor　下的　node_modules 　和　package-lock.josn吗？

**Comment by fujuhao** [comment]
ngx-ueditor下只有node_modules 没有　package-lock.json  不过移除node_modules后加载成功

**Comment by fujuhao** [comment]
图片上传：
我的配置：serverUrl: 'http://api.xxxxxx.com/api/v1/uploads'
uploads　写成了　uplodas  不过改过来之后没有报错了，

但是点击单图上传没任何反应．．．．

官方文档：
前端配置项说明
以下的"URL"是ueditor.config.js文件所在目录
UEDITOR_HOME_URL {Path String} [默认值：根据config文件路径自动获取] // 为编辑器实例添加一个路径，这个不能被注释

serverUrl {Path String} [默认值：URL + "php/controller.php"] // 服务器统一请求接口路径

angular一般都调用api　那这个URL指向的是angular项目的根目录　显然不行的

能不能在你的demo里配置一下图片上传的功能，祥细说明一下怎么配置完成一个图片上传功能　
调用一个编辑器，缺少这个图片上传，基本上无用

**Comment by fujuhao** [comment]
点击多图时加载css路径错误：http://localhost:4200/assets/plugins/ueditor/dialogs/image/assets/plugins/ueditor/themes/default/dialogbase.css?cache=0.265426674773398
