### ISSUE TITLE
将angular2.X升级到4.X以后报错

### ISSUE THREAD

**Issue by long-hai-yang** [cipchk/ngx-ueditor#4]
报错内容：`ERROR TypeError: Cannot read property 'Instance' of undefined`
代码：`this.full.Instance.setHeight(500);`
   `this.full.Instance.execCommand('insertHtml', img);`
`this.full.Instance.execCommand( 'insertimage', {
                src:success.data['url'],
                width:'300px',
                height:'200px'
            });`

**Comment by cipchk** [comment]
github 上的 DEMO 就是 `4.0.1` 版本，能否提供更细的代码。

我无法重现这个错误。

**Comment by long-hai-yang** [comment]
`我的版本是`4.1.3`,然后用法首先在要用的Module中引入：
`import { UEditorModule } from 'ngx-ueditor';`
`UEditorModule.forRoot({`
        path: './assets/ueditor/',
        options: {
            themePath: './assets/ueditor/themes/',
        },
    }),`
然后在用的组件中：
`import { UEditorComponent } from 'ngx-ueditor';`
`export class AddGraphicMateria {
   @ViewChild('full') full: UEditorComponent;
   constructor(public http:Http,private router: Router,private route: ActivatedRoute,private _state: GlobalState,private el: ElementRef) {
     this.full.Instance.setHeight(500);//这里就开始报错了，后面只要用到这个this.full.Instance实例的都报错
}
}`

**Comment by cipchk** [comment]
不要在 `constructor` 中访问 UEditor 实例对象，因为这个时候还未初始化。

你可以使用 `(onReady)` 事件，这个时候可以确保初始化完成。

**Comment by long-hai-yang** [comment]
谢谢，按此方法解决了
