### ISSUE TITLE
_this.onChange is not a function

### ISSUE THREAD

**Issue by silentmx** [cipchk/ngx-ueditor#40]
ueditor.addListener('contentChange', function () {
     _this.value = ueditor.getContent();
     _this.zone.run(function () { return _this.onChange(_this.value); });
 });

**Comment by cipchk** [comment]
能否提供一个完整的示例。

**Comment by silentmx** [comment]
项目有些大，我在使用得时候估计没有使用onChange，导致onChange由于没有值报错。我手动下载了项目给onChange默认值就可以正常使用了。
private onChange: (value: string) => void; 改为下面这个
private onChange: (value: string) => void = (_: any) => {};
