### ISSUE TITLE
angular4.4.6按照官方README记录的方法引入，报错误

### ISSUE THREAD

**Issue by qq1209974887** [cipchk/ngx-ueditor#41]
按照官方的README文档，在引入阶段即报错，错误截图如下：
![image](https://user-images.githubusercontent.com/18743063/43580849-65cb20ae-9689-11e8-8ae8-e9a779a66110.png)

使用的angular版本及相关依赖：
![image](https://user-images.githubusercontent.com/18743063/43580966-c0392946-9689-11e8-8989-3db4312221b2.png)

**Comment by cipchk** [comment]
使用最新版本，另外目前最新版本只支持Angular6
