### ISSUE TITLE
内容输入不识别括号 ()

### ISSUE THREAD

**Issue by tianxiaozi** [cipchk/ngx-ueditor#42]
在文本结尾输入 ()
不会触发onContentChange  
ngModel也没有 ()
导致上传服务器的内容都缺少 ()

**Comment by tianxiaozi** [comment]
单独输入!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!也不识别
!@#$%^&*()_+ 都不会触发onContentChange  ngModel也是空的

**Comment by cipchk** [comment]
Angular 依赖的是 `contentChange` 事件，这个问题是 UEditor 本身的问题，参考：

https://tieba.baidu.com/p/4230693833?red_tag=2782100746&traceid=

的解法。

或者提交前做一些数据获取动作，参考[getContent](https://github.com/cipchk/ngx-ueditor/blob/master/src/app/components/demo.component.ts#L35)。
