### ISSUE TITLE
ngx-ueditor2.1.2使用bootstrap模态框在关闭时报错

### ISSUE THREAD

**Issue by zhangjinsong** [cipchk/ngx-ueditor#43]
![image](https://user-images.githubusercontent.com/12949599/46676687-9f11f800-cc13-11e8-9c6c-af9413875bc1.png)

这是第一次关闭时报的错误
![image](https://user-images.githubusercontent.com/12949599/46676714-acc77d80-cc13-11e8-93aa-2efe0e285f36.png)

这是第二次打开时报的错误
![image](https://user-images.githubusercontent.com/12949599/46676588-6e31c300-cc13-11e8-9a53-159124bf78fa.png)

这是第二次关闭时报的错误
之后就不能再打开模态框了
再issue上无法找到相似的错误
这是我的package.json信息
![image](https://user-images.githubusercontent.com/12949599/46676781-c9fc4c00-cc13-11e8-863f-e0015cc0af1d.png)

**Comment by cipchk** [comment]
一个讨论很久的 https://github.com/angular/angular/issues/14252 的问题。

你可以尝试在移除模态框之前先使用 `*ngIf` 注销后再关闭。

**Comment by zhangjinsong** [comment]
尝试使用*ngIf还是不能解决这个问题

**Comment by zhangjinsong** [comment]
不过可以多次点击了

**Comment by zhangjinsong** [comment]
![image](https://user-images.githubusercontent.com/12949599/46678389-1bf2a100-cc17-11e8-92e7-d179cc869291.png)


这是我添加的代码   再关闭之前she设置未false

**Comment by cipchk** [comment]
我尝试增加一个示例 https://cipchk.github.io/ngx-ueditor/#/modal ，但未发现你的问题。

**Comment by cipchk** [comment]
我增加一个 https://stackblitz.com/edit/ngx-ueditor 在线测试示例，你可以根据该示例进一步重现你的问题。

**Comment by zhangjinsong** [comment]
你是否能添加[(ngModel)]="fullSource"然后重试

**Comment by zhangjinsong** [comment]
https://ngx-ueditor.stackblitz.io/
这是我错误展现的在线测试示例

**Comment by zhangjinsong** [comment]
https://stackblitz.com/edit/ngx-ueditor-5l5t9d
这是我整理的在线测试示例，里面能重复我提出的错误。拜托了

**Comment by zhangjinsong** [comment]
![image](https://user-images.githubusercontent.com/12949599/46710225-8f2cff00-cc79-11e8-919a-40285b575eaf.png)
升级后报错
