### ISSUE TITLE
ngx-ueditor使用ngx-bootstrap的modal在滚动时工具栏无法跟随

### ISSUE THREAD

**Issue by zhangjinsong** [cipchk/ngx-ueditor#44]
![image](https://user-images.githubusercontent.com/12949599/46781230-2d40c800-cd53-11e8-9159-7b62b5a8831b.png)
这是console的报错信息
![image](https://user-images.githubusercontent.com/12949599/46781330-a2ac9880-cd53-11e8-937b-b9eb432b9173.png)
这是报错后的样式
![image](https://user-images.githubusercontent.com/12949599/46781346-bd7f0d00-cd53-11e8-98d6-bcdbc3fb864e.png)
这是package.json信息

**Comment by zhangjinsong** [comment]
并且在使用多个组件时通过[(ngModal)]无法获取到值

**Comment by zhangjinsong** [comment]
![image](https://user-images.githubusercontent.com/12949599/46784551-2faa1e80-cd61-11e8-8b90-2570d158ee19.png)
这是提交的值和输入值
![image](https://user-images.githubusercontent.com/12949599/46784579-4b152980-cd61-11e8-9980-ed2804d5ad2b.png)
这是设置代码，请问这个需要怎么处理，谢谢

**Comment by cipchk** [comment]
1、无法跟随没办法解决。
2、请呈现相应示例。

> 其实个人不建议在 Modal 中使用，或者可以考虑 https://github.com/cipchk/ngx-tinymce，UEditor 官网已经不再维护了。
