### ISSUE TITLE
百分之五十机会出现UE.getEditor is not a function

### ISSUE THREAD

**Issue by YuChao-Go** [cipchk/ngx-ueditor#47]
运行自己的工程，和下载的ngx-ueditor的demo，然后刷新页面，还是有百分之五十的机会出现UE.getEditor is not a function的情况。看了代码和下边这个pr是一样的，还是会出现。
[https://github.com/cipchk/ngx-ueditor/pull/45](url)

**Comment by cipchk** [comment]
试着在 `index.html` 的 `head` 加入:

```html
<script src="./assets/ueditor/ueditor.config.js"></script>
```

然后移除 `UEditorModule.forRoot` 当中的 `ueditor.config.js` 部分。

**Comment by YuChao-Go** [comment]
[``](https://github.com/cipchk/ngx-ueditor/issues/47#issuecomment-447783316)按照您的这种方式改了之后，每次都会提示UE.getEditor is not a function了

**Comment by cipchk** [comment]
那我无能为力了，目测我们项目当中并没有遇到这类问题。

**Comment by YuChao-Go** [comment]
作了很多测试，只有在firefox上才会出现UE.getEditor is not a function的情况。测试过Firefox版本52.0、60.0、64.2
Chrome和360浏览器都没有出现。

**Comment by cipchk** [comment]
是否在 firefox 下，资源加载顺序与其他浏览器不同呢？

**Comment by sfwjiao** [comment]
ueditor.config.js 文件里面有一段代码：
`window.UE = { getUEBasePath: getUEBasePath };`
如果ueditor.config.js在ueditor.all.min.js之后加载的话会将UE对象覆盖掉，因此会报“UE.getEditor is not a function”的错误。
可以将这段代码改成：
`window.UE = window.UE || {};`
`window.UE.getUEBasePath = getUEBasePath;`
