### ISSUE TITLE
问题请教：怎么初始化内容

### ISSUE THREAD

**Issue by YuChao-Go** [cipchk/ngx-ueditor#48]
我现在要从后端获取一段文字显示在content中，作为初始化内容。请问我应该怎么做呢？
现在的做法是：在component.ts的

> ngOnInit() { this.httpClient.get('/getDocTxt')
    .subscribe((docTxt: Map<String, String>) => {
        if (docTxt !== null) {
          this.txt= docTxt.txt;
        } 
      });}

获取需要初始化显示的内容
然后用
`<ueditor (onReady)="setContentData(false)" ...`
onReady方法设置内容；但是这样service获取数据有延时，就总是会报错，显示不了初始化数据。

**Comment by cipchk** [comment]
```html
<ueditor [(ngModel)]="txt"></ueditor>
```
