### ISSUE TITLE
使用ngx-ueditor前端上传图片如何配置

### ISSUE THREAD

**Issue by rogueRabbit** [cipchk/ngx-ueditor#5]
我现在页面中引入了ngx-ueditor；之前的上传图片是通过js调用接口来上传的，ngx-ueditor改如何配置？
使用umeditor时，我是这样配置的
this.editor = UE.getEditor('newsEditor',{
            uploadProc: this.uploadProc.bind(this),
            imageFieldName: "file",
            imagePath: "",
            //图片修正地址，引用了fixedImagePath,如有特殊需求，可自行配置
            //工具栏上的所有的功能按钮和下拉框，可以在new编辑器的实例时选择自己需要的从新定义
            toolbar: [
                'source | bold italic underline strikethrough | superscript subscript | forecolor backcolor | removeformat |',
                'insertorderedlist insertunorderedlist | fontsize',
                '| justifyleft justifycenter justifyright justifyjustify  ',
                '| image video fullscreen '
            ]
        });

uploadProc是我在写的一个上传图片的方法

**Comment by cipchk** [comment]
如需要二次开发上传图片功能，可以参考 [二次开发](https://github.com/cipchk/ngx-ueditor#二次开发) 说明。

**Comment by forecho** [comment]
是否能给一个实例代码？上传图片这个功能真的很常用，看了二次开发的说明，还是没看懂怎么加上传图片。

**Comment by cipchk** [comment]
github 提供的 demo 仓库，无法实现上传功能，其实就是一个URL地址的配置；

**Comment by forecho** [comment]
不用 demo 也行，是否能提供一个上传图片配置的说明文档，感谢，确实不知道如何下手。
