### ISSUE TITLE
在按住shfit的情况下输入的字符没有改变ngModel

### ISSUE THREAD

**Issue by zd5043039119** [cipchk/ngx-ueditor#50]
以https://cipchk.github.io/ngx-ueditor/#/ 为例
如果按住shift打大写字母或符号,最后放开shift后,富文本编辑器和结果不同步

**Comment by zd5043039119** [comment]
看了一下应该是Ueditor本身的问题

**Comment by genhaodegenhao** [comment]
怎样解决的
