### ISSUE TITLE
指定ueditor.js路径目录的问题

### ISSUE THREAD

**Issue by Gznq** [cipchk/ngx-ueditor#6]
你好，配置路径path: 'assets/ueditor/'的时候我发现请求
ueditor.all.js，ueditor.config.js，会加多一个“/”，
例如http://localhost:3000/assets/js/ueditor//ueditor.config.js

如果配置路径改成path: 'assets/ueditor'的时候。语言包路径又错误了
js/ueditorlang/zh-cn/zh-cn.js  少了一个“/”

**Comment by cipchk** [comment]
多个 `//ueditor.config.js` 并不影响加载，不过我会修复该问题。
